GPF

diff --git a/download/tmp/scripts/goodbad b/download/tmp/scripts/goodbad
--- a/download/tmp/scripts/goodbad
+++ b/download/tmp/scripts/goodbad
@@ -2,9 +2,12 @@
 ################################################################################
 #@(#) goodbad: track which library routines have been built successfully in SQLite database
 ################################################################################
+#echo "GOODBAD: $*"
 cd $HOME/LIBRARY || exit
 export TMPFILE=/tmp/$(uuidgen).txt
-################################################################################
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
 PARSE(){
 #ident  "@(#)parse: crack Unix-like commands (V1.2 19960401 John S. Urban)"
 # Revision 1.0 Copyright (c) 1991, by John S. Urban
@@ -53,6 +56,7 @@ usage="$0 basename [ -keyword1 [value1] -keyword2 [value2] [ -keyword3 [value3] 
 #    TESTIT_cxxx='OOPS'
 #-------------------------------------------------------------------------------
 export PARSE_PROMPT=${PARSE_PROMPT:-NO}
+####################################################################################################################################
 OUTVALUE(){
 NAME="$1"
 VALUE="$2"
@@ -70,6 +74,7 @@ cat <<EOF
 $NAME='${VALUE}'
 EOF
 }
+####################################################################################################################################
 #-------------------------------------------------------------------------------
 if tty -s
 then
@@ -195,69 +200,47 @@ done
 #-------------------------------------------------------------------------------
 exit
 }
-################################################################################
-# parse command arguments
-export ALL="$*"
-export GOODBAD_00
-export GOODBAD_version
-export GOODBAD_help
-export GOODBAD_edit 
-export GOODBAD_html 
-export GOODBAD_delete 
-export GOODBAD_section
-export GOODBAD_description 
-export GOODBAD_documentation
-export GOODBAD_filename 
-export GOODBAD_library 
-export GOODBAD_ufpp 
-export GOODBAD_ccall
-export GOODBAD_archive 
-export DATE=$(date +%Y/%m/%d\ %H:%M:%S)
-ANSWER=$(PARSE GOODBAD -delete NO -html NO -edit NO -help NO -version NO -debug NO \
-    -description -documentation -filename -library -ufpp -ccall -archive  -browse NO \
-    -section 3\
-    -00 $*)
-eval ${ANSWER}
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
+DEBUG(){
+cat <<EOF
+<<<<<<<<<<<<<<<<
+ENTRYNAME ...... ${ENTRYNAME}
+DESCRIPTION .... $GOODBAD_description
+DOCUMENTATION .. $GOODBAD_documentation
+FILENAME ....... $GOODBAD_filename
+LIBRARY ........ $GOODBAD_library
+UFPP ........... $GOODBAD_ufpp
+CCALL .......... $GOODBAD_ccall
+ARCHIVE ........ $GOODBAD_archive
+SECTION ........ $GOODBAD_section
+MAN ............ $GOODBAD_man
+>>>>>>>>>>>>>>>>
 
-export DESCRIPTION="$GOODBAD_description"
-export DOCUMENTATION="$GOODBAD_documentation"
-export FILENAME="$GOODBAD_filename"
-export LIBRARY="$GOODBAD_library"
-export UFPP="$GOODBAD_ufpp"
-export CCALL="$GOODBAD_ccall"
-export ARCHIVE="$GOODBAD_archive"
-export SECTION="$GOODBAD_section"
-
-set -- ${GOODBAD_00:-DEFAULT}
-ENTRYNAME=${1}
-# remove leading underscore
-case "$ENTRYNAME" in
-   _*)ENTRYNAME=${ENTRYNAME/_/}
-esac
-
-STATUS=${2:-0}
-case "$STATUS" in
-bad)STATUS='-1';;
-good)STATUS='1';;
-start)STATUS='0';;
-esac
-STATUS=${STATUS/good/}
-STATUS=${STATUS/bad/-}
-#  0: started
-#  1: passed
-# -1: failed
-
-export ENTRYNAME=${ENTRYNAME}.$SECTION
-################################################################################
-# if debug flag is set display variables set and exit
-if [ "$GOODBAD_debug" != 'NO' ]
-then
-   echo PARAMETERS ARE $ANSWER
-   env |grep '^GOODBAD_'
-   echo "ENTRYNAME=$ENTRYNAME"
-   echo "STATUS=$STATUS"
-   exit
-fi
+EOF
+}
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
+SHOW(){
+echo "SHOW $*"
+for NAMES_TO_SHOW in $*
+do
+   sqlite3 goodbad.db <<EOF
+-- one item per line
+.mode line
+SELECT * FROM tests WHERE entryname='$NAMES_TO_SHOW';
+EOF
+done
+}
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
 ####################################################################################################################################
 # function to display help text
 HELP(){
@@ -268,36 +251,43 @@ NAME
                 the results of simple tests run on the routines
 
 SYNOPSIS
-      goodbad  [entryname numeric_status ]
+      goodbad  [entryname [status] ]
                [-edit]
                [-html]
                [-delete]
+               [-show]
                [-help]
                [-version]
 
 DESCRIPTION
        entryname [numeric_status]
 
-       Note that a leading _ will be deleted from the
-       entryname
-          numeric_status
-            0     means a unit test was begun
-         bad1     negative values mean a test has failed
-        good1     positive values mean a test has passed
+       Note that a entryname with a leading _ will be ignored
 
-       -edit
-              if specified edit file as simple text file
-       -delete
-              if specified remove entryname 
-       -section     section number. Defaults to 3
-       -description 
+          numeric_status
+       start        means a unit test was begun
+         bad[N]     means a test has failed
+        good[N]     means  a test has passed
+
+       -edit        if specified edit file as simple text file
+       -delete      if specified remove entryname
+       -show
+
+       Descriptions:
+
+       -section        section number. Defaults to 3
+       -description
        -documentation
-       -filename      
-       -library  
-       -ufpp      
-       -ccall      
-       -archive     
-       
+       -man            update all descriptions from man(1) pages
+
+       Processing:
+
+       -filename
+       -library
+       -ufpp
+       -ccall
+       -archive
+
        --help display this help and exit
 
        --version
@@ -322,6 +312,8 @@ EXAMPLE:
 EOF
 }
 ####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
 # display version information
 VERSION(){
 cat <<EOF
@@ -333,6 +325,8 @@ FILE:       $0
 EOF
 }
 ####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
 # display version information
 VERSION(){
 cat <<EOF
@@ -343,6 +337,8 @@ AUTHOR:     John S. Urban
 FILE:       $0
 EOF
 }
+####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
 ####################################################################################################################################
 CREATE(){
 echo 'creating goodbad'
@@ -364,7 +360,97 @@ CREATE TABLE IF NOT EXISTS tests(
 EOF
 }
 ####################################################################################################################################
+#()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()#
+####################################################################################################################################
+
+####################################################################################################################################
+####################################################################################################################################
+# parse command arguments
+export ALL="$*"
+export GOODBAD_00
+export GOODBAD_version
+export GOODBAD_help
+export GOODBAD_edit
+export GOODBAD_html
+export GOODBAD_delete
+export GOODBAD_section
+export GOODBAD_description
+export GOODBAD_documentation
+export GOODBAD_man
+export GOODBAD_filename
+export GOODBAD_library
+export GOODBAD_ufpp
+export GOODBAD_ccall
+export GOODBAD_archive
+export GOODBAD_show
+export DATE=$(date +%Y/%m/%d\ %H:%M:%S)
+ANSWER=$(PARSE GOODBAD \
+	-delete NO \
+	-html NO \
+	-edit NO \
+	-help NO \
+	-version NO \
+        -debug NO \
+        -man NO \
+        -browse NO \
+        -show NO \
+        -description \
+        -documentation \
+        -filename \
+        -library \
+        -ufpp \
+        -ccall \
+        -archive  \
+        -section 3 \
+        -00 $*)
+eval ${ANSWER}
+
+export DESCRIPTION="$GOODBAD_description"
+export DOCUMENTATION="$GOODBAD_documentation"
+export MAN_DESCRIPTION="$GOODBAD_man"
+export FILENAME="$GOODBAD_filename"
+export LIBRARY="$GOODBAD_library"
+export UFPP="$GOODBAD_ufpp"
+export CCALL="$GOODBAD_ccall"
+export ARCHIVE="$GOODBAD_archive"
+export SECTION="$GOODBAD_section"
+
+set -- ${GOODBAD_00:-DEFAULT}
+ENTRYNAME=${1}
+#####################################
+# remove double leading underscore entries
+case "$ENTRYNAME" in
+   __*)
+      echo "$ENTRYNAME ignored by $0" 1>&2
+      ENTRYNAME=${ENTRYNAME/_/}
+      exit
+  ;;
+esac
+#####################################
+STATUS=${2:-' '}
+case "$STATUS" in
+bad)STATUS='-1';;
+good)STATUS='1';;
+start)STATUS='0';;
+esac
+STATUS=${STATUS/good/}
+STATUS=${STATUS/bad/-}
+#  0: started
+#  1: passed
+# -1: failed
+
+export ENTRYNAME=${ENTRYNAME}.$SECTION
 ################################################################################
+# if debug flag is set display variables set and exit
+if [ "$GOODBAD_debug" != 'NO' ]
+then
+   echo PARAMETERS ARE $ANSWER
+   env |grep '^GOODBAD_'
+   echo "ENTRYNAME=$ENTRYNAME"
+   echo "STATUS=$STATUS"
+   exit
+fi
+####################################################################################################################################
 # display help text if -help parameter is present
 case "$GOODBAD_help" in
 NO);;
@@ -376,7 +462,7 @@ case "$GOODBAD_version" in
 NO);;
 *) VERSION; exit;;
 esac
-################################################################################
+####################################################################################################################################
 # If database does not exist initialize it
 if [ ! -f goodbad.db -o ! -s goodbad.db ]
 then
@@ -400,8 +486,7 @@ EOF
 #cygstart /tmp/status_$(logname).html
    exit
 fi
-################################################################################
-# if 
+####################################################################################################################################
 if [ "$GOODBAD_html" != 'NO' ]
 then
    (
@@ -418,7 +503,7 @@ EOF
 #cygstart /tmp/status_$(logname).html
    exit
 fi
-################################################################################
+####################################################################################################################################
 # if -edit switch specified edit file as simple text file
 if [ "$GOODBAD_edit" != 'NO' ]
 then
@@ -433,12 +518,12 @@ EOF
    rm -f $TMPFILE )
    exit
 fi
-################################################################################
-# Database schema 
+####################################################################################################################################
+# Database schema
 # entryname â|date  â|descriptionâ|documentationâ|filenameâ|libraryâ|ufppâ|ccallâ|archiveâ|status
 ################################################################################
 ################################################################################
-# if -delete switch specified 
+# if -delete switch specified
 if [ "$GOODBAD_delete" != 'NO' ]
 then
    echo "DELETE FROM tests WHERE entryname='$ENTRYNAME';"
@@ -446,35 +531,60 @@ then
    exit
 fi
 ################################################################################
+# if -show switch specified
+if [ "$GOODBAD_show" != 'NO' ]
+then
+   SHOW $GOODBAD_show
+   exit
+fi
+################################################################################
+STATUS=${STATUS/ /}
 #------------------------------------------------------------------------------#
-case "$STATUS" in
-DEFAULT)
+case "${STATUS}${ALL}" in
+DEFAULT*|-[a-zA-Z]*)
+echo 'No status'
+exit
 ;;
-*)
-   printf "$0: $ENTRYNAME $STATUS\n"
+*-*)
+   printf "$0: $ENTRYNAME $STATUS $ALL\n"
    #set -x
 
-   sqlite3 goodbad.db "INSERT INTO tests ( entryname, date, status ) VALUES ( '$ENTRYNAME'  , '$DATE', $STATUS) ;" >/dev/null 2>&1
+   if [ "$STATUS" != '' ]
+   then
+      sqlite3 goodbad.db "INSERT INTO tests ( entryname, date, status ) VALUES ( '$ENTRYNAME'  , '$DATE', $STATUS) ;" >/dev/null 2>&1
+      sqlite3 goodbad.db "UPDATE tests SET entryname='$ENTRYNAME', date='$DATE', status=$STATUS  WHERE entryname='$ENTRYNAME';"
+   else
+      sqlite3 goodbad.db "INSERT INTO tests ( entryname, date ) VALUES ( '$ENTRYNAME'  , '$DATE' ) ;" >/dev/null 2>&1
+      sqlite3 goodbad.db "UPDATE tests SET entryname='$ENTRYNAME', date='$DATE' WHERE entryname='$ENTRYNAME';"
+   fi
 
-   sqlite3 goodbad.db "UPDATE tests SET entryname='$ENTRYNAME', date='$DATE', status=$STATUS  WHERE entryname='$ENTRYNAME';"
-   [ "$DESCRIPTION" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET description='$DESCRIPTION' WHERE entryname='$ENTRYNAME';"
+   if [ "$DESCRIPTION" != DEFAULT -a "$DESCRIPTION" != '' ] 
+   then
+      sqlite3 goodbad.db "UPDATE tests SET description='$DESCRIPTION' WHERE entryname='$ENTRYNAME';"
+   fi
    [ "$DOCUMENTATION" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET documentation='$DOCUMENTATION' WHERE entryname='$ENTRYNAME';"
-   [ "$FILENAME" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET filename='$FILENAME' WHERE entryname='$ENTRYNAME';"
-   [ "$LIBRARY" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET library='$LIBRARY' WHERE entryname='$ENTRYNAME';"
-   [ "$UFPP" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET ufpp='$UFPP' WHERE entryname='$ENTRYNAME';"
-   [ "$CCALL" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET ccall='$CCALL' WHERE entryname='$ENTRYNAME';"
-   [ "$ARCHIVE" != DEFAULT ] && sqlite3 goodbad.db "UPDATE tests SET archive='$ARCHIVE' WHERE entryname='$ENTRYNAME';"
+   [ "$FILENAME" != DEFAULT ]      && sqlite3 goodbad.db "UPDATE tests SET filename='$FILENAME' WHERE entryname='$ENTRYNAME';"
+   [ "$LIBRARY" != DEFAULT ]       && sqlite3 goodbad.db "UPDATE tests SET library='$LIBRARY' WHERE entryname='$ENTRYNAME';"
+   [ "$UFPP" != DEFAULT ]          && sqlite3 goodbad.db "UPDATE tests SET ufpp='$UFPP' WHERE entryname='$ENTRYNAME';"
+   [ "$CCALL" != DEFAULT ]         && sqlite3 goodbad.db "UPDATE tests SET ccall='$CCALL' WHERE entryname='$ENTRYNAME';"
+   [ "$ARCHIVE" != DEFAULT ]       && sqlite3 goodbad.db "UPDATE tests SET archive='$ARCHIVE' WHERE entryname='$ENTRYNAME';"
 
 
-   echo "data for $ENTRYNAME is"
-   sqlite3 -header -column goodbad.db  'select * from tests where entryname="'$ENTRYNAME'";'
-
-   if [ "$STATUS" -ge 0 ]
+   #echo "data for $ENTRYNAME is"
+   #sqlite3 -header -column goodbad.db  'select * from tests where entryname="'$ENTRYNAME'";'
+   if [ "${STATUS:-0}" -ge 0 ]
    then
 	   exit 0
    else
 	   exit 1
    fi
+;;
+#------------------------------------------------------------------------------#
+*\ good|*\ bad)
+;;
+*)
+   echo "[$STATUS $ALL]data for $ENTRYNAME is"
+   SHOW ${ENTRYNAME}
 ;;
 #------------------------------------------------------------------------------#
 esac
